//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputActions/InputMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMap"",
    ""maps"": [
        {
            ""name"": ""GearChange"",
            ""id"": ""7945de2d-af1f-4a3b-9684-4f26de37afab"",
            ""actions"": [
                {
                    ""name"": ""GearUp"",
                    ""type"": ""Button"",
                    ""id"": ""87981ee3-71bd-4dcf-b592-f245335cd3bf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GearDown"",
                    ""type"": ""Button"",
                    ""id"": ""d70e28b6-f737-44ed-83dc-1fea288d50e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5768d6df-0a64-48c9-947e-34dfe11c1d6e"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GearUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae3b034d-f581-4f6c-a150-6bc8fbebabe0"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GearUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13793721-12f1-45f6-9176-bc83217c4b65"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GearDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1b1c1d5-9c59-45a5-91c6-61df4a17964f"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GearDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GearChange
        m_GearChange = asset.FindActionMap("GearChange", throwIfNotFound: true);
        m_GearChange_GearUp = m_GearChange.FindAction("GearUp", throwIfNotFound: true);
        m_GearChange_GearDown = m_GearChange.FindAction("GearDown", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GearChange
    private readonly InputActionMap m_GearChange;
    private List<IGearChangeActions> m_GearChangeActionsCallbackInterfaces = new List<IGearChangeActions>();
    private readonly InputAction m_GearChange_GearUp;
    private readonly InputAction m_GearChange_GearDown;
    public struct GearChangeActions
    {
        private @InputMap m_Wrapper;
        public GearChangeActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @GearUp => m_Wrapper.m_GearChange_GearUp;
        public InputAction @GearDown => m_Wrapper.m_GearChange_GearDown;
        public InputActionMap Get() { return m_Wrapper.m_GearChange; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GearChangeActions set) { return set.Get(); }
        public void AddCallbacks(IGearChangeActions instance)
        {
            if (instance == null || m_Wrapper.m_GearChangeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GearChangeActionsCallbackInterfaces.Add(instance);
            @GearUp.started += instance.OnGearUp;
            @GearUp.performed += instance.OnGearUp;
            @GearUp.canceled += instance.OnGearUp;
            @GearDown.started += instance.OnGearDown;
            @GearDown.performed += instance.OnGearDown;
            @GearDown.canceled += instance.OnGearDown;
        }

        private void UnregisterCallbacks(IGearChangeActions instance)
        {
            @GearUp.started -= instance.OnGearUp;
            @GearUp.performed -= instance.OnGearUp;
            @GearUp.canceled -= instance.OnGearUp;
            @GearDown.started -= instance.OnGearDown;
            @GearDown.performed -= instance.OnGearDown;
            @GearDown.canceled -= instance.OnGearDown;
        }

        public void RemoveCallbacks(IGearChangeActions instance)
        {
            if (m_Wrapper.m_GearChangeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGearChangeActions instance)
        {
            foreach (var item in m_Wrapper.m_GearChangeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GearChangeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GearChangeActions @GearChange => new GearChangeActions(this);
    public interface IGearChangeActions
    {
        void OnGearUp(InputAction.CallbackContext context);
        void OnGearDown(InputAction.CallbackContext context);
    }
}
