//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputActions/InputMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMap"",
    ""maps"": [
        {
            ""name"": ""Controll"",
            ""id"": ""84bef2c1-ae0e-4947-b229-3bd2bb904b38"",
            ""actions"": [
                {
                    ""name"": ""ViewPointMove"",
                    ""type"": ""Value"",
                    ""id"": ""02d63f5c-7cc1-4011-af64-d410c306ea00"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ChangePerson"",
                    ""type"": ""Button"",
                    ""id"": ""4ff5d6cb-f567-4921-b282-2616bbb067a7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Pad"",
                    ""id"": ""2c6f4d17-effb-4723-a2ad-30715b21db60"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ViewPointMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b3c0e55f-3bf8-4cb9-825a-a9a8ade10c8e"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ViewPointMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d778b6b2-175f-4a6e-ad64-530209f9846c"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ViewPointMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a215b5d8-c0c7-466b-9dd1-7c47ffd0146d"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ViewPointMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c12cb5ee-71e2-4a35-b64c-7b292b15730b"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ViewPointMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Mouse"",
                    ""id"": ""b033a937-0de6-4c44-9aaa-a0f8e5073bce"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ViewPointMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b7189068-ae4a-4f5a-8835-649f340aec60"",
                    ""path"": ""<Mouse>/delta/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ViewPointMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9986cdce-2b19-42ed-afaf-ecad9daced5d"",
                    ""path"": ""<Mouse>/delta/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ViewPointMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8d763b44-84a8-4ea6-8f7d-ac6ac6b4ce72"",
                    ""path"": ""<Mouse>/delta/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ViewPointMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9b151004-706c-4351-8ba4-af510ced5d35"",
                    ""path"": ""<Mouse>/delta/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ViewPointMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""48c38bc0-3e05-4ce6-9fdf-e492f2352c74"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangePerson"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6972e01-1864-4d24-8925-3a1d2bea9773"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangePerson"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""GearChange"",
            ""id"": ""89ffee06-b951-4868-b197-d2442c6cdf7b"",
            ""actions"": [
                {
                    ""name"": ""GearUp"",
                    ""type"": ""Button"",
                    ""id"": ""2a6b87f5-5169-48ef-87fa-98de80f4fea7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GearDown"",
                    ""type"": ""Button"",
                    ""id"": ""34b16852-0d78-4057-a520-4ce991a1855f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""424d0184-56cc-4a73-8f9a-10e2b7bf68e0"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GearUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a6217e6-c388-4967-b044-2f2f12793631"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GearUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91c81675-310c-4f73-8fc5-809d19f2f7bf"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GearDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""446bcc48-c2d5-4aa5-8975-3b132fe2955c"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GearDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Engine"",
            ""id"": ""248f8af9-0c0b-4404-9370-fc43efa17742"",
            ""actions"": [
                {
                    ""name"": ""Axel"",
                    ""type"": ""Value"",
                    ""id"": ""7e03ec55-1c0d-445f-964d-406d105e2c85"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Brake"",
                    ""type"": ""Value"",
                    ""id"": ""be74dd14-6a34-4bfe-8cdd-a2f87354a6b8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ee07af35-bb80-41f2-a018-f726528c600a"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ddec980-d2c9-4581-8d3f-585076bba080"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db7514df-54df-4b84-a89b-97f6be855920"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab7b1644-c9ea-42be-8359-7239302f9f69"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Controll
        m_Controll = asset.FindActionMap("Controll", throwIfNotFound: true);
        m_Controll_ViewPointMove = m_Controll.FindAction("ViewPointMove", throwIfNotFound: true);
        m_Controll_ChangePerson = m_Controll.FindAction("ChangePerson", throwIfNotFound: true);
        // GearChange
        m_GearChange = asset.FindActionMap("GearChange", throwIfNotFound: true);
        m_GearChange_GearUp = m_GearChange.FindAction("GearUp", throwIfNotFound: true);
        m_GearChange_GearDown = m_GearChange.FindAction("GearDown", throwIfNotFound: true);
        // Engine
        m_Engine = asset.FindActionMap("Engine", throwIfNotFound: true);
        m_Engine_Axel = m_Engine.FindAction("Axel", throwIfNotFound: true);
        m_Engine_Brake = m_Engine.FindAction("Brake", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Controll
    private readonly InputActionMap m_Controll;
    private List<IControllActions> m_ControllActionsCallbackInterfaces = new List<IControllActions>();
    private readonly InputAction m_Controll_ViewPointMove;
    private readonly InputAction m_Controll_ChangePerson;
    public struct ControllActions
    {
        private @InputMap m_Wrapper;
        public ControllActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @ViewPointMove => m_Wrapper.m_Controll_ViewPointMove;
        public InputAction @ChangePerson => m_Wrapper.m_Controll_ChangePerson;
        public InputActionMap Get() { return m_Wrapper.m_Controll; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControllActions set) { return set.Get(); }
        public void AddCallbacks(IControllActions instance)
        {
            if (instance == null || m_Wrapper.m_ControllActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ControllActionsCallbackInterfaces.Add(instance);
            @ViewPointMove.started += instance.OnViewPointMove;
            @ViewPointMove.performed += instance.OnViewPointMove;
            @ViewPointMove.canceled += instance.OnViewPointMove;
            @ChangePerson.started += instance.OnChangePerson;
            @ChangePerson.performed += instance.OnChangePerson;
            @ChangePerson.canceled += instance.OnChangePerson;
        }

        private void UnregisterCallbacks(IControllActions instance)
        {
            @ViewPointMove.started -= instance.OnViewPointMove;
            @ViewPointMove.performed -= instance.OnViewPointMove;
            @ViewPointMove.canceled -= instance.OnViewPointMove;
            @ChangePerson.started -= instance.OnChangePerson;
            @ChangePerson.performed -= instance.OnChangePerson;
            @ChangePerson.canceled -= instance.OnChangePerson;
        }

        public void RemoveCallbacks(IControllActions instance)
        {
            if (m_Wrapper.m_ControllActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IControllActions instance)
        {
            foreach (var item in m_Wrapper.m_ControllActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ControllActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ControllActions @Controll => new ControllActions(this);

    // GearChange
    private readonly InputActionMap m_GearChange;
    private List<IGearChangeActions> m_GearChangeActionsCallbackInterfaces = new List<IGearChangeActions>();
    private readonly InputAction m_GearChange_GearUp;
    private readonly InputAction m_GearChange_GearDown;
    public struct GearChangeActions
    {
        private @InputMap m_Wrapper;
        public GearChangeActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @GearUp => m_Wrapper.m_GearChange_GearUp;
        public InputAction @GearDown => m_Wrapper.m_GearChange_GearDown;
        public InputActionMap Get() { return m_Wrapper.m_GearChange; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GearChangeActions set) { return set.Get(); }
        public void AddCallbacks(IGearChangeActions instance)
        {
            if (instance == null || m_Wrapper.m_GearChangeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GearChangeActionsCallbackInterfaces.Add(instance);
            @GearUp.started += instance.OnGearUp;
            @GearUp.performed += instance.OnGearUp;
            @GearUp.canceled += instance.OnGearUp;
            @GearDown.started += instance.OnGearDown;
            @GearDown.performed += instance.OnGearDown;
            @GearDown.canceled += instance.OnGearDown;
        }

        private void UnregisterCallbacks(IGearChangeActions instance)
        {
            @GearUp.started -= instance.OnGearUp;
            @GearUp.performed -= instance.OnGearUp;
            @GearUp.canceled -= instance.OnGearUp;
            @GearDown.started -= instance.OnGearDown;
            @GearDown.performed -= instance.OnGearDown;
            @GearDown.canceled -= instance.OnGearDown;
        }

        public void RemoveCallbacks(IGearChangeActions instance)
        {
            if (m_Wrapper.m_GearChangeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGearChangeActions instance)
        {
            foreach (var item in m_Wrapper.m_GearChangeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GearChangeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GearChangeActions @GearChange => new GearChangeActions(this);

    // Engine
    private readonly InputActionMap m_Engine;
    private List<IEngineActions> m_EngineActionsCallbackInterfaces = new List<IEngineActions>();
    private readonly InputAction m_Engine_Axel;
    private readonly InputAction m_Engine_Brake;
    public struct EngineActions
    {
        private @InputMap m_Wrapper;
        public EngineActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Axel => m_Wrapper.m_Engine_Axel;
        public InputAction @Brake => m_Wrapper.m_Engine_Brake;
        public InputActionMap Get() { return m_Wrapper.m_Engine; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(EngineActions set) { return set.Get(); }
        public void AddCallbacks(IEngineActions instance)
        {
            if (instance == null || m_Wrapper.m_EngineActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_EngineActionsCallbackInterfaces.Add(instance);
            @Axel.started += instance.OnAxel;
            @Axel.performed += instance.OnAxel;
            @Axel.canceled += instance.OnAxel;
            @Brake.started += instance.OnBrake;
            @Brake.performed += instance.OnBrake;
            @Brake.canceled += instance.OnBrake;
        }

        private void UnregisterCallbacks(IEngineActions instance)
        {
            @Axel.started -= instance.OnAxel;
            @Axel.performed -= instance.OnAxel;
            @Axel.canceled -= instance.OnAxel;
            @Brake.started -= instance.OnBrake;
            @Brake.performed -= instance.OnBrake;
            @Brake.canceled -= instance.OnBrake;
        }

        public void RemoveCallbacks(IEngineActions instance)
        {
            if (m_Wrapper.m_EngineActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IEngineActions instance)
        {
            foreach (var item in m_Wrapper.m_EngineActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_EngineActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public EngineActions @Engine => new EngineActions(this);
    public interface IControllActions
    {
        void OnViewPointMove(InputAction.CallbackContext context);
        void OnChangePerson(InputAction.CallbackContext context);
    }
    public interface IGearChangeActions
    {
        void OnGearUp(InputAction.CallbackContext context);
        void OnGearDown(InputAction.CallbackContext context);
    }
    public interface IEngineActions
    {
        void OnAxel(InputAction.CallbackContext context);
        void OnBrake(InputAction.CallbackContext context);
    }
}
